image: node:latest

stages:
  - init
  - build
  - production
  
init:
  stage: init
  script:
    - npm install
  
build:
  stage: build
  script:
    - npm run build-babel

production:
  type: deploy
  stage: production
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/fleetwood.git
    - git push -f heroku master
  only:
    - master
