# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'npm install'
      - run:
          name: Building
          command: 'npm run heroku-postbuild'
      # - run:
      #     name: Build webpack
      #     command: 'npm run start'
  
workflows:
  version: 2
  deploy:
    jobs:
      - build