# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  setup:
    jobs:
      - setup:
          steps:
            - run:
                name: npm install
                command: 'npm install'
  build:
    jobs:
      - setup
      - build:
          requires: 
            - setup
          steps:
            - run:
                name: building
                command: 'npm run build'